name: Tests

on:
  pull_request:
  push:
    branches:
      - master

# One active job per PR, cancel older ones on push
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Build BikeStreets
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: .github/workflows/xcode_select.sh
      - uses: extractions/netrc@v1
        with:
          machine: api.mapbox.com
          username: mapbox
          password: ${{ secrets.MAPBOX_API_KEY }}
      - name: Build App
        run: |
          # Build the app
          xcodebuild build \
            -project 'bikestreets-ios.xcodeproj' \
            -scheme 'BikeStreets' \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGN_IDENTITY=""
